### ISSUE TITLE
[5.7] configure: error: cannot find sources (libUseful) in . or ..

### ISSUE THREAD

**Issue by andreasstieger** [ColumPaget/libUseful#8]
This is new in 5.7:

````
./configure
configure: error: cannot find sources (libUseful) in . or ..
````

With and without `autoreconf -fiv`.

**Comment by ColumPaget** [comment]
Hi Andreas, I believe this is already fixed in 5.8. Autoconf went crazy on me for a while, working on some machines, not on others, and ignoring some lines in the configure.ac file completely. I couldn't figure it out, and eventually had to give into it's demands that I run autoupgrade and change to modern autoconf idiom, which I didn't want to do because I feared it then wouldn't work with older autoconf systems. But, needs must when the devil drives. So I think this is fixed in 5.8, along with a bug that was causing a build fail when built without openssl.
